
# Form Settings 

  # Command
form_command_name: ['form']
form_command_description: '§7Form example command!' 

  # Form [LongForm]
long_form_title: 'Example LongForm' 
long_form_content: '§7Any text:' 
long_form_buttons: 
  form_button_1:
    text: 'Button with url image' 
    image: 'url|https://picsum.photos/200/200'
  form_button_2:
    text: ['§l§Button with resourcepack image', 'Content example'] 
    image: 'path|textures/items/diamond_sword.png'

  # Form [ModalForm]
modal_form_title: 'Example ModalForm' 
modal_form_content: '§7Any text:' 
modal_form_buttons: 
  button_yes:
    text: 'Button Yes'
  button_no:
    text: 'Button No'



# Menu settings 

  # Command
menu_command_name: ['menu']
menu_command_description: '§7Menu example command!' 

  # Menu 
menu_title: 'Example Menu'
menu_contents: [] # Use Item_Serielized